export const INDIAN_COLLEGES = [
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "National Institute of Technology (NIT) Trichy",
  "National Institute of Technology (NIT) Karnataka",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Rourkela",
  "Birla Institute of Technology and Science (BITS) Pilani",
  "Birla Institute of Technology and Science (BITS) Goa",
  "Birla Institute of Technology and Science (BITS) Hyderabad",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "Anna University, Chennai",
  "Jadavpur University, Kolkata",
  "Vellore Institute of Technology (VIT) Vellore",
  "Vellore Institute of Technology (VIT) Chennai",
  "SRM Institute of Science and Technology",
  "Manipal Institute of Technology",
  "Amity University",
  "Lovely Professional University (LPU)",
  "Chandigarh University",
  "Thapar Institute of Engineering and Technology",
  "Osmania University, Hyderabad",
  "Jawaharlal Nehru Technological University (JNTU) Hyderabad",
  "Jawaharlal Nehru Technological University (JNTU) Kakinada",
  "University of Delhi (DU)",
  "Banaras Hindu University (BHU)",
  "Aligarh Muslim University (AMU)",
  "Jamia Millia Islamia",
  "Savitribai Phule Pune University",
  "Mumbai University",
  "Calcutta University",
  "Madras University",
  "Christ University, Bangalore",
  "Jain University, Bangalore",
  "PES University, Bangalore",
  "RV College of Engineering, Bangalore",
  "MS Ramaiah Institute of Technology, Bangalore",
  "BMS College of Engineering, Bangalore",
  "VNR Vignana Jyothi Institute of Engineering and Technology",
  "Chaitanya Bharathi Institute of Technology (CBIT)",
  "Vasavi College of Engineering, Hyderabad"
];
